### ISSUE TITLE
Test script rendering

### ISSUE THREAD

**Issue by shntnu** [broadinstitute/jump_hub#107]
https://github.com/broadinstitute/jump_hub/blob/main/.github/workflows/build_website.yml already implicitly tests if notebooks runnable, but I wonder if we should test this directly?

The notebooks should be expected to be runnable, with pyproject.toml specified, so this workflow would be a thing to run each time

Not urgent but #99 got me thinking we should directly test (and without the nix env) 

```yml
name: Test Notebook Rendering

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-render:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
    
    - name: Set up Python
      run: uv python install
    
    - name: Install project and dependencies
      run: |
        uv sync --dev
        uv pip install jupytext
    
    - name: Test notebook execution
      run: uv run jupytext --execute scripts/*.py
```
